kind: PersistentVolume
apiVersion: v1
metadata:
  name: resel-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/reselmnt/reseldata"